(function() {var implementors = {};
implementors["cupid"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.VersionInformation.html' title='cupid::VersionInformation'>VersionInformation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.ExtendedProcessorSignature.html' title='cupid::ExtendedProcessorSignature'>ExtendedProcessorSignature</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.ThermalPowerManagementInformation.html' title='cupid::ThermalPowerManagementInformation'>ThermalPowerManagementInformation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.StructuredExtendedInformation.html' title='cupid::StructuredExtendedInformation'>StructuredExtendedInformation</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cupid/enum.CacheLineAssociativity.html' title='cupid::CacheLineAssociativity'>CacheLineAssociativity</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.CacheLine.html' title='cupid::CacheLine'>CacheLine</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.TimeStampCounter.html' title='cupid::TimeStampCounter'>TimeStampCounter</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cupid/struct.PhysicalAddressSize.html' title='cupid::PhysicalAddressSize'>PhysicalAddressSize</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
